[tool.pylint.main]
max-line-length = "88"

disable = [
    "missing-function-docstring",
    "missing-module-docstring",
    "missing-class-docstring"
]

good-names = [
    "a",
    "b",
    "e",
    "f",
    "i",
    "j",
    "x",
    "y",   
    "z"
]